/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import java.awt.Color;

/**
 *
 * @author maxid
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
       
        
//new CambiaPanel(escritorio,frameObra);
       
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBack = new java.awt.Panel();
        escritorio = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnLabelCliente = new rsbuttom.RSButtonMetro();
        btnLabelObra = new rsbuttom.RSButtonMetro();
        btnRemito1 = new rsbuttom.RSButtonMetro();
        laminaPrincipalAzul = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnLamina = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        panelBack.setBackground(new java.awt.Color(255, 255, 255));
        panelBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        escritorio.setPreferredSize(new java.awt.Dimension(640, 410));
        escritorio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 69));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(24, 19, 48));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIOLETA/antialiasing_rendering2.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIOLETA/ant.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIOLETA/atom.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(67, 67, 67)
                .addComponent(jLabel2)
                .addGap(39, 39, 39))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 90, 100, 440));

        jPanel2.setBackground(new java.awt.Color(24, 19, 48));
        jPanel2.setForeground(new java.awt.Color(24, 19, 48));

        btnLabelCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIOLETA/cliente.png"))); // NOI18N
        btnLabelCliente.setText("Cliente");
        btnLabelCliente.setActionCommand("");
        btnLabelCliente.setColorBorde(null);
        btnLabelCliente.setColorHover(new java.awt.Color(24, 19, 48));
        btnLabelCliente.setColorNormal(new java.awt.Color(24, 19, 48));
        btnLabelCliente.setColorPressed(new java.awt.Color(24, 19, 48));
        btnLabelCliente.setColorTextHover(new java.awt.Color(0, 236, 154));
        btnLabelCliente.setColorTextNormal(new java.awt.Color(153, 153, 153));
        btnLabelCliente.setColorTextPressed(new java.awt.Color(24, 19, 48));
        btnLabelCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLabelCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLabelCliente.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnLabelCliente.setIconTextGap(25);

        btnLabelObra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIOLETA/obra.png"))); // NOI18N
        btnLabelObra.setText("Obra");
        btnLabelObra.setActionCommand("");
        btnLabelObra.setColorHover(new java.awt.Color(24, 19, 48));
        btnLabelObra.setColorNormal(new java.awt.Color(24, 19, 48));
        btnLabelObra.setColorPressed(new java.awt.Color(24, 19, 48));
        btnLabelObra.setColorTextHover(new java.awt.Color(0, 236, 154));
        btnLabelObra.setColorTextNormal(new java.awt.Color(153, 153, 153));
        btnLabelObra.setColorTextPressed(new java.awt.Color(24, 19, 48));
        btnLabelObra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLabelObra.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLabelObra.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnLabelObra.setIconTextGap(25);

        btnRemito1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIOLETA/remito.png"))); // NOI18N
        btnRemito1.setText("Remito");
        btnRemito1.setActionCommand("");
        btnRemito1.setColorHover(new java.awt.Color(24, 19, 48));
        btnRemito1.setColorNormal(new java.awt.Color(24, 19, 48));
        btnRemito1.setColorPressed(new java.awt.Color(24, 19, 48));
        btnRemito1.setColorTextHover(new java.awt.Color(0, 236, 154));
        btnRemito1.setColorTextNormal(new java.awt.Color(153, 153, 153));
        btnRemito1.setColorTextPressed(new java.awt.Color(24, 19, 48));
        btnRemito1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRemito1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRemito1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnRemito1.setIconTextGap(25);
        btnRemito1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRemito1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnLabelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnLabelObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnRemito1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(379, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLabelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLabelObra, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemito1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 950, 100));

        laminaPrincipalAzul.setBackground(new java.awt.Color(24, 0, 74));
        laminaPrincipalAzul.setForeground(new java.awt.Color(51, 31, 48));
        laminaPrincipalAzul.setLayout(new java.awt.BorderLayout());
        jPanel3.add(laminaPrincipalAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 850, 440));

        escritorio.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 530));

        panelBack.add(escritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 950, 530));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLamina.setBackground(new java.awt.Color(51, 51, 51));
        btnLamina.setForeground(new java.awt.Color(0, 176, 255));
        btnLamina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        btnLamina.setBorder(null);
        btnLamina.setContentAreaFilled(false);
        btnLamina.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnLamina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaminaActionPerformed(evt);
            }
        });
        jPanel1.add(btnLamina, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 50));

        panelBack.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemito1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemito1MousePressed
        this.btnLabelObra.setSelected(false);
        this.btnRemito1.setSelected(true);
        this.btnLabelCliente.setSelected(false);
        
    }//GEN-LAST:event_btnRemito1MousePressed

    private void btnLaminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaminaActionPerformed
       
    }//GEN-LAST:event_btnLaminaActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public rsbuttom.RSButtonMetro btnLabelCliente;
    public rsbuttom.RSButtonMetro btnLabelObra;
    public javax.swing.JButton btnLamina;
    public rsbuttom.RSButtonMetro btnRemito1;
    public javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    public javax.swing.JPanel laminaPrincipalAzul;
    public java.awt.Panel panelBack;
    // End of variables declaration//GEN-END:variables
    public FrameObra frameObra;

    public rsbuttom.RSButtonMetro btnObra;
    public rsbuttom.RSButtonMetro btnRemito;
    

}
