/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaMain;

import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author ferc
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        setLayout(new BorderLayout());
       
       
        
        
//new CambiaPanel(escritorio,frameObra);
       
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        escritorio = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        btnLabelCliente = new rsbuttom.RSButtonMetro();
        btnLabelObra = new rsbuttom.RSButtonMetro();
        btnRemito1 = new rsbuttom.RSButtonMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        escritorio.setBackground(new java.awt.Color(102, 0, 102));
        escritorio.setPreferredSize(new java.awt.Dimension(970, 460));
        escritorio.setLayout(new java.awt.BorderLayout());
        jPanel1.add(escritorio, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(24, 19, 48));
        jPanel2.setForeground(new java.awt.Color(24, 19, 48));

        btnLabelCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIOLETA/cliente.png"))); // NOI18N
        btnLabelCliente.setText("Cliente");
        btnLabelCliente.setActionCommand("");
        btnLabelCliente.setColorBorde(null);
        btnLabelCliente.setColorHover(new java.awt.Color(24, 19, 48));
        btnLabelCliente.setColorNormal(new java.awt.Color(24, 19, 48));
        btnLabelCliente.setColorPressed(new java.awt.Color(24, 19, 48));
        btnLabelCliente.setColorTextHover(new java.awt.Color(0, 236, 154));
        btnLabelCliente.setColorTextNormal(new java.awt.Color(153, 153, 153));
        btnLabelCliente.setColorTextPressed(new java.awt.Color(24, 19, 48));
        btnLabelCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLabelCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLabelCliente.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnLabelCliente.setIconTextGap(25);

        btnLabelObra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIOLETA/obra.png"))); // NOI18N
        btnLabelObra.setText("Obra");
        btnLabelObra.setActionCommand("");
        btnLabelObra.setColorHover(new java.awt.Color(24, 19, 48));
        btnLabelObra.setColorNormal(new java.awt.Color(24, 19, 48));
        btnLabelObra.setColorPressed(new java.awt.Color(24, 19, 48));
        btnLabelObra.setColorTextHover(new java.awt.Color(0, 236, 154));
        btnLabelObra.setColorTextNormal(new java.awt.Color(153, 153, 153));
        btnLabelObra.setColorTextPressed(new java.awt.Color(24, 19, 48));
        btnLabelObra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLabelObra.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLabelObra.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnLabelObra.setIconTextGap(25);

        btnRemito1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIOLETA/remito.png"))); // NOI18N
        btnRemito1.setText("Remito");
        btnRemito1.setActionCommand("");
        btnRemito1.setColorHover(new java.awt.Color(24, 19, 48));
        btnRemito1.setColorNormal(new java.awt.Color(24, 19, 48));
        btnRemito1.setColorPressed(new java.awt.Color(24, 19, 48));
        btnRemito1.setColorTextHover(new java.awt.Color(0, 236, 154));
        btnRemito1.setColorTextNormal(new java.awt.Color(153, 153, 153));
        btnRemito1.setColorTextPressed(new java.awt.Color(24, 19, 48));
        btnRemito1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRemito1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRemito1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnRemito1.setIconTextGap(25);
        btnRemito1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRemito1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnLabelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnLabelObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnRemito1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLabelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLabelObra, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemito1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemito1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemito1MousePressed
        this.btnLabelObra.setSelected(false);
        this.btnRemito1.setSelected(true);
        this.btnLabelCliente.setSelected(false);

    }//GEN-LAST:event_btnRemito1MousePressed

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public rsbuttom.RSButtonMetro btnLabelCliente;
    public rsbuttom.RSButtonMetro btnLabelObra;
    public rsbuttom.RSButtonMetro btnRemito1;
    public javax.swing.JDesktopPane escritorio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
    public FrameObra frameObra;
    public FrameCliente frameCliente;
    public FrameRemito frameRemito;
    public rsbuttom.RSButtonMetro btnObra;
    public rsbuttom.RSButtonMetro btnRemito;
    

}
